# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parkingID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('long', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('parking_type', models.CharField(choices=[('WILSON', 'Wilson'), ('SECURE', 'Secure Parking')], max_length=150)),
                ('places_of_interest', models.TextField()),
                ('uri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RatePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RateType',
            fields=[
                ('rateID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('day_of_week', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('rate_type', models.CharField(choices=[('Hourly', 'Hourly'), ('Flat', 'Flat')], max_length=50)),
                ('label', models.CharField(default='', max_length=50)),
                ('parkingID', models.ForeignKey(db_column='parkingID', on_delete=django.db.models.deletion.CASCADE, to='parker.Parking')),
            ],
        ),
        migrations.AddField(
            model_name='rateprice',
            name='rateID',
            field=models.ForeignKey(db_column='rateID', on_delete=django.db.models.deletion.CASCADE, to='parker.RateType'),
        ),
        migrations.AlterUniqueTogether(
            name='ratetype',
            unique_together=set([('parkingID', 'day_of_week', 'rate_type', 'label')]),
        ),
        migrations.AlterUniqueTogether(
            name='rateprice',
            unique_together=set([('duration', 'rateID')]),
        ),
    ]
