# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratetype',
            unique_together=set([('parkingID', 'day_of_week', 'type', 'label')]),
        ),
    ]
