# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetype',
            name='day_of_week',
            field=models.SmallIntegerField(default=0),
        ),
    ]
