# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parker', '0002_auto_20160120_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='parking',
            name='places_of_interest',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ratetype',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='ratetype',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
