 version: '2'
 services:
   parker:
     build: .
     working_dir: /carparker
     #command: "/carparker/bootstrap.sh"
     volumes:
       - .:/carparker
     ports:
       - "8000:8000"
     tty: true
     depends_on:
       - nginx
   nginx:
     build: ./nginx
     #volumes:
    #   - .:/carparker
     ports:
       - "80:80"
