version: '2'
services:
    parker:
        build: ./container-app
        working_dir: /carparker
        command: "/carparker/container-app/bootstrap.sh"
        volumes:
            - .:/carparker
        #ports:
        #  - "8030:8030"
        tty: true
    nginx:
        build: ./container-nginx
        ports:
            - "80:80"
        volumes:
            - .:/carparker 
