version: '2'
services:
    parker:
        build: ./container-app
        working_dir: /carparker
        command: "/carparker/container-app/bootstrap.sh"
        volumes:
            - .:/carparker
        ports:
          - "8030:8030"
        tty: true
        depends_on:
            - parker-db
    nginx:
        build: ./container-nginx
        volumes:
            - .:/carparker
        ports:
            - "80:80"
        depends_on:
            - parker
    parker-db:
        build: ./container-db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=parker
            - MYSQL_USER=carparker
            - MYSQL_PASSWORD=carparker
